@url = https://localhost:3000/graphql
#@url = https://gener-iert-12345.herokuapp.com/graphql
### Neuen Film anlegen
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createFilm(
    titel: "Fight Club"
    datum: "1999-11-11"
    kategorien: ["Action", "Thriller"]
    sprache: ENGLISCH
    dauer: 139
    homepage: "https://acme.com/"
  ) {
    id
  }
}

### Vorhandenen Film aktualisieren
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateFilm(
    _id: "00000000-0000-0000-0000-000000000003",
    titel: "Star Wars IV: a new hope",
    datum: "1978-02-09"
    kategorien: ["Science Fiction", "Action"]
    sprache: ENGLISCH
    dauer: 125
    homepage: "https://acme.com/"
    version: 0
  ) {
    version
  }
}

### Vorhandenen Film loeschen
POST {{url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteFilm(id: "00000000-0000-0000-0000-000000000004")
}
